// export enum Role {
//   SUDO_ADMIN = 'SUDO_ADMIN',
//   SUPER_ADMIN = 'SUPER_ADMIN',
//   ADMIN = 'ADMIN',
//   USER = 'USER',
//   DATA_ENTRY = 'DATA_ENTRY',
// }

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum Environment {
  DEVELOPMENT = 'DEVELOPMENT',
  PRODUCTION = 'PRODUCTION',
}

export enum AssessmentCommitteeType {
  WARD = 'WARD',
  GAUNPALIKA = 'GAUNPALIKA',
  MUNICIPALITY = 'MUNICIPALITY',
  DISTRICT = 'DISTRICT',
  PROVINCE = 'PROVINCE',
  FEDERAL = 'FEDERAL',
}

export enum MediaType {
  BULK_UPLOAD = 'BULK_UPLOAD',
  RESOURCE = 'RESOURCE',
  INDUSTRY_REGISTRATION_CERTIFICATE = 'INDUSTRY_REGISTRATION_CERTIFICATE',
  INDUSTRY_RENEWAL_CERTIFICATE = 'INDUSTRY_RENEWAL_CERTIFICATE',
  PAN_CERTIFICATE = 'PAN_CERTIFICATE',
  AUDIT_REPORT = 'AUDIT_REPORT',
  TAX_CLEARANCE_CERTIFICATE = 'TAX_CLEARANCE_CERTIFICATE',
  REPRESENTATIVE_CITIZENSHIP_FRONT = 'REPRESENTATIVE_CITIZENSHIP_FRONT',
  REPRESENTATIVE_CITIZENSHIP_BACK = 'REPRESENTATIVE_CITIZENSHIP_BACK',
  EMPLOYEE_SALARY_DETAILS = 'EMPLOYEE_SALARY_DETAILS',
  IT_INNOVATION_DECLARATION = 'IT_INNOVATION_DECLARATION',
  RAW_MATERIAL_PURCHASE_BILL = 'RAW_MATERIAL_PURCHASE_BILL',

  TERM_ACCEPTANCE = 'TERM_ACCEPTANCE',
  SIGNATURE = 'SIGNATURE',
  PROJECT_STAMP = 'PROJECT_STAMP',

  COMMITTEE_MEMBER_DOCUMENT = 'COMMITTEE_MEMBER_DOCUMENT',
}

export enum SMSMessageType {
  ACCOUNT_VERIFICATION = 'ACCOUNT_VERIFICATION',
  RESEND = 'RESEND',
  PASSWORD_RESET = 'PASSWORD_RESET',
  APPLICATION_SUBMISSION = 'APPLICATION_SUBMISSION',
  LOGIN_VERIFICATION = 'LOGIN_VERIFICATION',
}
