export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum Environment {
  DEVELOPMENT = 'DEVELOPMENT',
  PRODUCTION = 'PRODUCTION',
}

export enum MediaType {
  BULK_UPLOAD = 'BULK_UPLOAD',
  RESOURCE = 'RESOURCE',
  CITIZENSHIP_FRONT = 'CITIZENSHIP_FRONT',
  CITIZENSHIP_BACK = 'CITIZENSHIP_BACK',
  DALIT_CERTIFICATE = 'DALIT_CERTIFICATE',
  TRAINING_CERTIFICATE = 'TRAINING_CERTIFICATE',
  EDUCATIONAL_CERTIFICATE = 'EDUCATIONAL_CERTIFICATE',
  RECOMMENDATION_LETTER = 'RECOMMENDATION_LETTER',
  OTHER_DOCUMENT = 'OTHER_DOCUMENT',
}

export enum SMSMessageType {
  ACCOUNT_VERIFICATION = 'ACCOUNT_VERIFICATION',
  RESEND = 'RESEND',
  PASSWORD_RESET = 'PASSWORD_RESET',
  APPLICATION_SUBMISSION = 'APPLICATION_SUBMISSION',
  LOGIN_VERIFICATION = 'LOGIN_VERIFICATION',
}
